---
- name: Playbook for setting up scripts on servers (Ubuntu 22.04.1 LTS)
  hosts: servers
  become: true
  vars_files:
    - "group_vars/pi/vars.yml"

  tasks:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
    - name: Get Ansible fact - datetime
      no_log: true
      debug:
        var: ansible_date_time

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    - name: Install hwinfo, Java JDK, cron if absent
      apt:
        pkg:
          # Meta
          - hwinfo
          - cron
          # Java
          - openjdk-17-jre-headless
          # Docker
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          # Database
          - postgresql-common
          - postgresql-15
        state: present
        force_apt_get: true

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    - name: Create executable directories for executables, configs, logging, scripts
      file:
        path: ["{{ authapi_path }}", "{{ authapi_config_path }}", "{{ logs_path }}", "{{ scripts_path }}"]
        state: directory
        mode: "777"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    - name: Copy scripts to server
      copy:
        remote_src: false
        src: ./scripts
        dest: /var/www
        mode: "777"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
    - name: Cron job for starting AuthApi on reboot
      cron:
        name: Start AuthApi on boot
        special_time: reboot
        job: "{{ scripts_path }}/authapi_start.sh"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
    - name: Cron job for rotating log file
      cron:
        name: Rotate AuthApi.log
        special_time: monthly
        job: "{{ scripts_path }}/authapi_rotate_log.sh"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
    # Klogging requires an environment path to use logging setup file, does not allow for programmatically setting path. On first set, this requires a terminal reboot
    - name: Add env var for klogging
      lineinfile:
        path: "/etc/environment"
        line: "{{ item }}"
        create: true
      with_items:
        - "KLOGGING_CONFIG_PATH={{ klogging_config_path }}"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
    - name: Setup some basic info for AuthApi and software used
      become_method: su
      become_user: root
      lineinfile:
        path: "{{ server_info_path }}"
        line: "{{ item }}"
        create: true
      with_items:
        # Meta
        - "# AuthApi"
        - "API for recipes and planning menus."
        - "#### Software needed"
        - "- AuthApi jar file"
        - "- hwinfo"
        - "- openjdk-18-jre-headless"
        - "- cron"
        - "- python3"
        - "- docker"
        - "- SEQ for docker"
        - "- whatever came bundled in Ubuntu 22.04.1 LTS"
        - "#### Associated directories and files"
        - "- {{ authapi_path }}"
        - "- {{ logs_path }}"
        - "- {{ scripts_path }}"
        - "- {{ aliases }}"
        - "- {{ ansible_log_path }}"
        - "#### Running this project"
        - "- As long as all software is installed and port 9000 is free, simply run the following command (alias): $ restartauth"
        - "- Otherwise see the documentation on GitHub: https://github.com/gardehal/kotlin-auth-api"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
    # Note: Aliases requires reload of terminals, unsure if Ansible script may recognize them in first run
    - name: Setup file for aliases
      become_method: su
      become_user: root
      lineinfile:
        path: "{{ aliases }}"
        line: "{{ item }}"
        create: true
      with_items:
        # Meta
        - "alias reloadalias='. {{ aliases }} && echo \"Aliases reloaded\"'"
        - "alias ra='reloadalias'"
        # Logs
        - "alias logs='cd {{ logs_path }}'"
        - "alias ansiblelog='cat {{ ansible_log_path }}'"
        - "alias al='ansiblelog'"
        # Auth - API
        - "alias cdauthapi='cd {{ authapi_path }}'"
        - "alias cdca='cdauthapi'"
        - "alias restartauth='{{ scripts_path }}/authapi_stop.sh && echo \"Stopped, restarting...\" && sleep 1 && {{ scripts_path }}/authapi_start.sh'"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
    - name: Log setup
      become_method: su
      become_user: root
      lineinfile:
        path: "{{ ansible_log_path }}"
        line: "{{ item }}"
        create: true
      with_items:
        - "{{ ansible_date_time.iso8601 }} - Ansible setup, AuthApi"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
    - name: Reboot reminder
      debug:
        msg: "Reminder: Some steps require a reboot of the terminal or machine to fully activate."
